### ISSUE TITLE
add class on side of className in the props object when using variant

### ISSUE THREAD

**Issue by flozero** [busbud/tailwind-buddy#22]
Context: https://github.com/busbud/tailwind-buddy/issues/19

To be more "framework" agnostic like. It would be a better dx to make the className that is more a react way, just class to follow what html does.

As we don't want to break our apps using it. We would want to add it on side.

Required:
- class should override className
- ideally using typescript we would want to throw an error when using both? Or we do let people using both and just override using class

**Comment by zAlweNy26** [comment]
Imho, there should be two types, like `BaseVariants` and `JsxVariants`, so that it wouldn't be necessary to throw any errors. Let me know what you think.

**Comment by flozero** [comment]
I am not sure I quite understand what you are saying here. Can you give me a small example maybe ?
