### ISSUE TITLE
Interface extension improvments

### ISSUE THREAD

**Issue by chekromul** [busbud/tailwind-buddy#8]
### Preconditions

`"@busbud/tailwind-buddy": "^0.0.33"`

### Steps to reproduce

```ts
import { VariantsProps, compose } from "@busbud/tailwind-buddy";

interface FooBaseProps {
  someProp?: string;
}

const fooVariants = compose({
  slots: {
    root: "",
  },
  variants: {
    size: {
      md: {
        root: "text-size-150"
      },
    },
  },
  defaultVariants: {
    size: "md",
  },
  responsiveVariants: [],
})<FooBaseProps>();

type FooProps = VariantsProps<typeof fooVariants>;

export interface BarProps extends FooProps {}
```

### Actual result

Here's the error:

> TS2312: An interface can only extend an object type or intersection of object types with statically known members.

<details>
<summary>Screenshot</summary>
<img src="https://github.com/user-attachments/assets/f0e87fd7-f210-4b72-9d26-5be6bb74dcdd">
</details>

**Comment by flozero** [comment]
Its not something we do as we do need to type inside the variant definition the compound.

Thats the main difference with other libraries they don't support compound conditions with other props than the variants
