### ISSUE TITLE
Props doesn't work without `PropsWithChildren`

### ISSUE THREAD

**Issue by chekromul** [busbud/tailwind-buddy#9]
### Preconditions

`"@busbud/tailwind-buddy": "^0.0.33"`

### Steps to reproduce

```tsx
import { FC } from "react";
import { VariantsProps, compose } from "@busbud/tailwind-buddy";

interface FooBaseProps {
  someProp?: string;
}

const fooVariants = compose({
  slots: {
    root: "",
  },
  variants: {
    size: {
      md: {
        root: "text-size-150",
      },
    },
  },
  defaultVariants: {
    size: "md",
  },
  responsiveVariants: [],
})<FooBaseProps>();

type FooProps = VariantsProps<typeof fooVariants>;

export const Foo: FC<FooProps> = ({ someProp, size }) => (
  <div data-prop={someProp} data-size={size} />
);
```

### Actual result

Here's the error:

> TS2339: Property `someProp` does not exist on type
> ```ts
>MergedProps<FooBaseProps, {
>  size: {
>    md: {
>      root: string;
>    };
>  };
>}, never[]> | undefined
>

<details>
<summary>Error screenshot</summary>
<img src="https://github.com/user-attachments/assets/bb8513dc-526f-4cf9-b504-6544328787b2">
</details>

But if I add `PropsWithChildren` then everything works fine.

<details>
<summary>With <code>PropsWithChildren</code> screenshot</summary>
<img src="https://github.com/user-attachments/assets/fee2fc99-3180-45b5-8a1c-9ec17d8be760">
</details>

**Comment by flozero** [comment]
I am closing this as you can see https://github.com/busbud/tailwind-buddy/blob/main/packages/ui/src/components/Button/Button.variants.ts

I am not use with children but just React.FC

If you can provide a pr here with the type failing would help a lot
